-- Jalankan di Supabase SQL Editor sebelum memakai fitur "Threshold sebagai Parameter Admin".

-- Tabel konfigurasi threshold minimal lamaran Hiring, per Periode + Program Studi.
-- program_studi NULL artinya berlaku untuk SEMUA program studi pada periode tersebut.
CREATE TABLE IF NOT EXISTS threshold_hiring_config (
  id bigint generated by default as identity primary key,
  periode text NOT NULL,
  program_studi text,
  threshold_minimal integer NOT NULL CHECK (threshold_minimal > 0),
  keterangan text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (periode, program_studi)
);

-- Kolom baru pada hiring_tracer untuk menyimpan periode & prodi mahasiswa
-- (dipakai untuk mencocokkan konfigurasi threshold yang berlaku saat mahasiswa mendaftar).
ALTER TABLE hiring_tracer ADD COLUMN IF NOT EXISTS periode_yudisium text;
ALTER TABLE hiring_tracer ADD COLUMN IF NOT EXISTS program_studi text;

-- Catatan:
-- - threshold_minimal pada hiring_tracer TETAP ada (kolom lama) dan tetap dipakai sebagai
--   "snapshot" nilai threshold yang berlaku saat mahasiswa pertama kali mengisi status
--   pekerjaan. Ini supaya kalau admin mengubah konfigurasi di kemudian hari, mahasiswa yang
--   sedang berjalan tidak tiba-tiba berubah target thresholdnya.
-- - Kalau tidak ada konfigurasi yang cocok sama sekali (periode & prodi manapun), sistem
--   memakai nilai fallback 5 yang didefinisikan di app/lib/threshold.ts.

-- Contoh data awal (opsional, silakan sesuaikan / hapus):
-- INSERT INTO threshold_hiring_config (periode, program_studi, threshold_minimal, keterangan)
-- VALUES ('2026-Genap', NULL, 5, 'Default seluruh prodi periode Genap 2026');
